name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-22.04
    container: wpilib/roborio-cross-ubuntu:2025-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Add repository to git safe directories
      run: git config --global --add safe.directory $GITHUB_WORKSPACE
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Initialize and update submodules
      run: |
        git submodule init
        git submodule add https://github.com/SubZero-Robotics/2025-CommandRobot
        git submodule update
    - name: Compile and run tests on robot code
      run: ./gradlew build
